#!/bin/bash
if [ $(uname -s) == 'Darwin' ]; then
  alias ls="ls -G"
else
  alias ls="ls --color=auto"
fi

# system
alias ll="ls -la"
alias grep='grep --color=auto'

# projects
alias loggr='cd ~/workspace/loggregator'
alias gologgr='cd ~/workspace/go-loggregator/src/code.cloudfoundry.org/go-loggregator'
alias src='cd ~/workspace/loggregator/src/code.cloudfoundry.org/loggregator'
alias client="cd ~/workspace/go/src/code.cloudfoundry.org/go-loggregator"
alias ss="cd ~/workspace/cf-syslog-drain-release/src/code.cloudfoundry.org/scalable-syslog"
alias ssr="cd ~/workspace/cf-syslog-drain-release/"
alias sdr="cd ~/workspace/cf-syslog-drain-release/"
alias tools="cd ~/workspace/loggregator-tools"
alias dotfiles="cd ~/workspace/loggregator-dotfiles"

# repos
alias depl='cd ~/workspace/deployments-loggregator'
alias ci='cd ~/workspace/loggregator-ci'
alias cfd='cd ~/workspace/cf-deployment'

