#!/bin/bash
if [ $(uname -s) == 'Darwin' ]; then
  alias ls="ls -G"
else
  alias ls="ls --color=auto"
fi

# system
alias ll="ls -la"
alias grep='grep --color=auto'
alias nocaps='/usr/bin/setxkbmap -layout us -option ctrl:nocaps'

# projects
alias loggr='cd ${HOME}/workspace/loggregator-release'
alias gologgr='cd ${HOME}/workspace/go/src/code.cloudfoundry.org/go-loggregator'
alias src='cd ${HOME}/workspace/loggregator-release/src/code.cloudfoundry.org/loggregator'
alias glc="cd ${HOME}/workspace/go/src/code.cloudfoundry.org/go-log-cache"
alias ss="cd ${HOME}/workspace/cf-syslog-drain-release/src/code.cloudfoundry.org/scalable-syslog"
alias ssr="cd ${HOME}/workspace/cf-syslog-drain-release/"
alias sdr="cd ${HOME}/workspace/cf-syslog-drain-release/"
alias tools="cd ${HOME}/workspace/loggregator-tools"
alias dotfiles="cd ${HOME}/workspace/loggregator-dotfiles"
alias nnn="cd ${HOME}/workspace/noisy-neighbor-nozzle-release/src/code.cloudfoundry.org/noisy-neighbor-nozzle"
alias nnnr="cd ${HOME}/workspace/noisy-neighbor-nozzle-release"
alias lcr="cd ${HOME}/workspace/log-cache-release"
alias lcs="cd ${HOME}/workspace/log-cache-release/src/code.cloudfoundry.org/log-cache"
alias lcli="cd ${HOME}/workspace/go/src/code.cloudfoundry.org/log-cache-cli"
alias latsr="cd ${HOME}/workspace/logging-acceptance-tests-release"
alias lats="cd ${HOME}/workspace/logging-acceptance-tests-release/src/code.cloudfoundry.org/logging-acceptance-tests"
alias draincli="cd ${HOME}/workspace/go/src/code.cloudfoundry.org/cf-drain-cli"
alias lar="cd ${HOME}/workspace/loggregator-agent-release"
alias lcats="cd ${HOME}/workspace/log-cache-acceptance-tests-release/src/github.com/cloudfoundry/log-cache-acceptance-tests"
alias lcatsr="cd ${HOME}/workspace/log-cache-acceptance-tests-release"

# repos
alias depl='cd ${HOME}/workspace/deployments-loggregator'
alias ci='cd ${HOME}/workspace/loggregator-ci'
alias cfd='cd ${HOME}/workspace/cf-deployment'
alias play='cd ${HOME}/workspace/deployments-loggregator/gcp/playground'
alias coconut='cd ${HOME}/workspace/deployments-loggregator/gcp/coconut-bbl'
alias one='cd ${HOME}/workspace/deployments-loggregator/gcp/ci-pool/one'
alias two='cd ${HOME}/workspace/deployments-loggregator/gcp/ci-pool/two'
alias cats="cd ${HOME}/workspace/go/src/github.com/cloudfoundry/cf-acceptance-tests"
alias locks="cd ${HOME}/workspace/loggregator-locks"

alias pbc='tmux show-buffer | DISPLAY=:0 xsel -b'

# quick logins
alias login='./cf_login'
alias PWS='cf login -a api.run.pivotal.io -u cf-lamb@pivotallabs.com'
alias cf-manifest='bosh -d cf manifest > manifest.yml && vim manifest.yml'
alias cf-deploy='bosh -d cf deploy manifest.yml'

function cdf() {
  cd $(dirname $1)
}
