#!/bin/bash
if [ $(uname -s) == 'Darwin' ]; then
  alias ls="ls -G"
else
  alias ls="ls --color=auto"
fi

alias ll="ls -la"
alias grep='grep --color=auto'
alias loggr='cd ~/workspace/loggregator'
alias depl='cd ~/workspace/deployments-loggregator'
alias ci='cd ~/workspace/loggregator-ci'

alias ss="cd ~/workspace/scalable-syslog-release/src/code.cloudfoundry.org/scalable-syslog"
alias ssr="cd ~/workspace/scalable-syslog-release/"
